### PR TITLE
Build Analytics Charts and Setup API Functions

### PR DESCRIPTION
**Pull request by MJAlperin23**

### CODE REVIEW

**Comment by michaelmachlin** [comment]
@MJAlperin23 you may merge

**Comment by michaelmachlin** [comment]
@MJAlperin23 it's lit

have at it

**Review by michaelmachlin — APPROVED** [review]
I approve
a
p
p
r
o
v
e

**Comment by michaelmachlin** [comment]
M i c k e y
i
c
k
e
y

**Comment by jfeiber** [comment]
In the future we should probably move that loop through the date range code to its own method so we aren't repeating code. The code that builds the map can probably be moved to its own method as well. That "01/02/2006" date format string should prolly also be a global const because it's used a bunch of times throughout `url_handlers.go`

**Pull request merged**
